Feat/pyinstaller
linsyking/CanvasHelper2 pull request #19
Opened 2023-09-02 07:44 UTC by zzjc1234

This pr modified canvas_app s.t. the code can be packed with pyinstaller

2023-09-02 13:43 UTC, linsyking commented
Have you tested whether pyinstaller can work on this?

2023-09-02 13:44 UTC, zzjc1234 commented
Yes, the exe works well.

2023-09-02 13:49 UTC, zzjc1234 commented
The updator may have some unknown problem, but the updator.py should be modified anyway. Maybe I will fix it in another pr.

2023-09-02 13:59 UTC, linsyking commented
For executables the old updater doesn't work because it is based on git

2023-09-02 14:01 UTC, linsyking commented
Maybe we can just remove git update logic when building for executables.

2023-09-02 14:08 UTC, zzjc1234 commented
It seems that I didn't solve the dependency well, currently the exe only works under the dir with canvas_mgr.py and etc. I will try to fix it.

2023-09-02 14:20 UTC, linsyking commented
Also we need to migrate some arguments from uvicorn to the executables, eg. the port and base_url

2023-09-02 14:40 UTC, linsyking commented
I think we can remove the updater support. It is not very helpful but needs git dependency.

2023-09-03 15:27 UTC, linsyking commented
do not merge until everything is set

2023-09-07 13:25 UTC, linsyking commented
Please fix the build error.

2023-09-07 14:32 UTC, linsyking commented
I think we should first merge it to the dev branch otherwise current users will be affected

2023-09-07 14:40 UTC, linsyking requested changes

2023-09-07 14:40 UTC, linsyking commented on start.py
> +            usr_host = net_config["host"]
If "host" is not a field in the json file, it will throw an  exception

2023-09-07 14:40 UTC, linsyking commented on start.py
> +                usr_port = 9283
Do not write duplicate code

2023-09-07 14:51 UTC, linsyking approved these changes

2024-01-16 11:27 UTC, zzjc1234 commented on start.py
> +                usr_port = 9283
fixed

2024-02-12 06:23 UTC, merged